version: "3.8"
services:
  php:
    #image: php:7.4-apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../sae501-502-theotime-martel/website:/var/www/html:z
    container_name: apachePHP

  mysql:
    image: mysql:latest  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nathiotime
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql:z
     
volumes: 
  db_data:


