version: "3.8"
services:
  nginx1:
    image: docker.io/library/nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../sae501-502-theotime-martel/public:/usr/share/nginx/html:z
      - ../sae501-502-theotime-martel/website/Pages/configNGINX:/etc/nginx/conf.d:z
      - ../sae501-502-theotime-martel/opensslkeys:/home:z
      - ../sae501-502-theotime-martel/composer:/usr/share/nginx/composer:z
    container_name: nginx1
    links:
      - php

  nginx2:
    image: docker.io/library/nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ../sae501-502-theotime-martel/public:/usr/share/nginx/html:z
      - ../sae501-502-theotime-martel/website/Pages/configNGINX:/etc/nginx/conf.d:z
      - ../sae501-502-theotime-martel/opensslkeys:/home:z
      - ../sae501-502-theotime-martel/composer:/usr/share/nginx/composer:z
    container_name: nginx2
    links:
      - php

  #haproxy:
    #image: haproxy:alpine
    #container_name: haproxy
    #ports:
      #- "80:80"
      #- "443:443"
    #volumes:
      #- ../sae501-502-theotime-martel/opensslkeys/myserver.pem:/etc/ssl/certs/myserver.pem:z
      #- ../sae501-502-theotime-martel/loadbalancing:/usr/local/etc/haproxy:z

  mysql:
    image: mysql:latest  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nathiotime
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql:z

  php:
    #image: php:8.2-fpm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    container_name: php
    volumes :
      - ../sae501-502-theotime-martel/public:/usr/share/nginx/html:z
      - ../sae501-502-theotime-martel/composer:/usr/share/nginx/composer:z
      - ../sae501-502-theotime-martel/website:/home:z
      - ../sae501-502-theotime-martel/.msmtprc:/root/.msmtprc:z
volumes: 
  db_data:
